src/routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CvController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\JobController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home.landing');
})->name('landing');
Route::get('/about', function () {
    return view('home.about');
})->name('about');
Route::get('/contact', function () {
    return view('home.contact');
})->name('contact');

Route::get('/findtalent', [ProfileController::class, 'getAll']);

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    // Jobs
    Route::get('/jobs', [JobController::class, 'index'])->name('jobs');
    Route::get('/myJobOffers', [JobController::class, 'myJobOffers'])->name('myJobOffers');
    Route::get('/createJob', [JobController::class, 'create'])->name('createJob');
    Route::post('/createJob', [JobController::class, 'store']);
    Route::get('/editJob/{id}', [JobController::class, 'edit']);
    Route::post('/saveJob/{id}', [JobController::class, 'update']);
    Route::post('/deleteJob/{id}', [JobController::class, 'destroy']);
    // Applications
    Route::get('/myApplications', [JobController::class, 'viewMyApplications'])->name('my.applications');
    Route::get('/applications', [JobController::class, 'jobApplications'])->name('applications');
    Route::post('/applyApplication/{id}', [JobController::class, 'createApplication']);
    // CV
    Route::get('/resume', [CvController::class, 'create'])->name('resume');
    Route::post('/resume', [CvController::class, 'store']);
    Route::post('/resumeUpdate', [CvController::class, 'update']);
    Route::get('/preview', [CvController::class, 'preview'])->name('preview');
    Route::get('/pdf', [CvController::class, 'createPDF']);



});

//FOR ADMIN ROUTES
Route::middleware(['auth','isAdmin'])->group(function(){
    // Categories
    Route::get('/categories', [CategoryController::class, 'index'])->name('categories');
    Route::get('/createCategory', [CategoryController::class, 'create']);
    Route::post('/createCategory', [CategoryController::class, 'store']);
    Route::get('/editCategory/{id}', [CategoryController::class, 'edit']);
    Route::post('/saveCategory/{id}', [CategoryController::class, 'update']);
    Route::post('/deleteCategory/{id}', [CategoryController::class, 'destroy']);

    Route::get('/admin/jobs', [JobController::class, 'getAllJobsAdmin'])->name('adminJobs');
    Route::post('/admin/deleteJob/{id}', [JobController::class, 'deleteJobAdmin']);
});


require __DIR__.'/auth.php';

src/app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
    ];
}

src/app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all(); 
        return view('category.index',['categories' => $categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.new');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'category_name'=>'required'
        ]); 

        $newCategory = Category::create([
            'name' => $request->category_name
        ]);

        $newCategory->save();
        return redirect('/categories')->with('success', 'Category added.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        return view('category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'category_name'=>'required'
        ]); 
        $category = Category::find($id);
        $category->name =  $request->category_name;
        $category->save();
 
        return redirect('/categories')->with('success', 'Category updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Category::find($id)->delete();
        return redirect('/categories')->with('success', 'Category removed.');
    }
}

src/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

src/resources/views/category/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Edit Category') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="row">
                <div class="col-sm-4 offset-sm-2">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                   <h1 class="">Edit Category</h1>
                    <div>
                        <form method="post" action="/saveCategory/{{ $category->id }}">
                            @csrf
                            <div class="mb-3">
                                <label for="category_name" class="form-label">Category Name: </label>
                                <input type="text" class="form-control" id="category_name" name="category_name" value="{{ $category->name }}">
                            </div>
                            <button type="submit" class="btn btn-primary">Update</button>
                        </form>
                    </div>
               </div>
            </div>
        </div>
    </div>

</x-app-layout>

src/resources/views/category/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Categories') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <a href="/createCategory" class="btn btn-primary mb-3">Add Category +</a>
            @if(session()->get('success'))
                <div class="alert alert-success">
                {{ session()->get('success') }}  
                </div>
            @endif
            <table class="table" id="category-table">
                <thead class="thead-light">
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Category Name</th>
                    <th scope="col">Actions</th>
                  </tr>
                </thead>
                <tbody>
                    @foreach ($categories as $category)
                        <tr>
                            <th scope="row">{{ $category->id }}</th>
                            <td>{{ $category->name }}</td>
                            <td class="d-flex">
                                <form action="/deleteCategory/{{$category->id}}" method="post">
                                    @csrf
                                    <button class="btn btn-sm btn-danger m-1"><i class="fa-solid fa-trash-can m-2"></i></button>
                                </form>
                                <a href="/editCategory/{{ $category->id }}" class="btn btn-sm btn-primary m-1"><i class="fa-solid fa-pen m-2"></i></a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
              </table>
        </div>
    </div>

</x-app-layout>
<script>
$(document).ready(function () {
    $('#category-table').DataTable();
});
</script>

src/resources/views/category/new.blade.php
<x-app-layout>


    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="row">
                <div class="col-sm-4 offset-sm-2">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                   <h1 class="">Add Category</h1>
                    <div>
                        <form method="post" action="/createCategory">
                            @csrf
                            <div class="mb-3">
                                <label for="category_name" class="form-label control-label">Category Name: </label>
                                <input type="text" class="form-control" id="category_name" name="category_name" required>
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
               </div>
            </div>
        </div>
    </div>
</x-app-layout>